In [5]:
import pandas as pd
import numpy as np

df_01_dws_user_active_1d_data = pd.read_parquet("output_aggregate_further_data\\01_dws_user_active_1d.parquet")
df_01_dws_user_active_1d_data.head()

,user_id,stat_date,first_active_date,last_active_date,event_cnt,session_cnt,task_touch_cnt,create_task_flag,complete_task_flag,delete_task_flag
0,user_006890,2026-08-23,2026-08-23,2026-08-23,2,2,2,0,0,0
1,user_001758,2026-08-23,2026-08-23,2026-08-23,4,4,4,1,1,1
2,user_009922,2026-08-23,2026-08-23,2026-08-23,6,5,5,1,0,1
3,user_003832,2026-08-23,2026-08-23,2026-08-23,3,3,2,1,0,0
4,user_008720,2026-08-23,2026-08-23,2026-08-23,3,3,3,0,1,0

In [6]:
df_01_dws_user_active_1d_data.columns

Index(['user_id', 'stat_date', 'first_active_date', 'last_active_date',
       'event_cnt', 'session_cnt', 'task_touch_cnt', 'create_task_flag',
       'complete_task_flag', 'delete_task_flag'],
      dtype='object')

In [7]:
df_02_dws_user_behavior_summary_data = pd.read_parquet("output_aggregate_further_data\\02_dws_user_behavior_summary.parquet")
df_02_dws_user_behavior_summary_data.head()

,user_id,total_event_cnt,active_day_cnt,last_active_date,create_task_cnt,complete_task_cnt,delete_task_cnt,completion_rate,avg_complete_duration_seconds
0,user_005612,52,32,2026-08-28,17,6,1,0.352941,1.036864e+06
1,user_002265,51,29,2026-08-29,12,4,2,0.333333,7.084858e+05
2,user_006539,72,43,2026-08-29,24,6,4,0.250000,1.513160e+06
3,user_001803,61,41,2026-08-29,22,7,0,0.318182,1.116904e+06
4,user_001244,70,35,2026-08-29,21,5,1,0.238095,1.544828e+06

In [8]:
df_02_dws_user_behavior_summary_data.columns

Index(['user_id', 'total_event_cnt', 'active_day_cnt', 'last_active_date',
       'create_task_cnt', 'complete_task_cnt', 'delete_task_cnt',
       'completion_rate', 'avg_complete_duration_seconds'],
      dtype='object')

In [9]:
df_03_dws_task_summary_1d_data = pd.read_parquet("output_aggregate_further_data\\03_dws_task_summary_1d.parquet")
df_03_dws_task_summary_1d_data.head()

,stat_date,task_created_cnt,task_completed_cnt,overdue_cnt,completion_rate,avg_complete_duration_seconds
0,2026-07-01,3007,945.0,660.0,0.314267,2.522681e+06
1,2026-07-02,3026,950.0,676.0,0.313946,2.558695e+06
2,2026-07-03,2980,995.0,706.0,0.333893,2.524033e+06
3,2026-07-04,2969,974.0,661.0,0.328057,2.391209e+06
4,2026-07-05,3091,1024.0,745.0,0.331284,2.417273e+06

In [10]:
df_03_dws_task_summary_1d_data.columns

Index(['stat_date', 'task_created_cnt', 'task_completed_cnt', 'overdue_cnt',
       'completion_rate', 'avg_complete_duration_seconds'],
      dtype='object')

In [11]:
df_04_dws_event_type_summary_1d_data = pd.read_parquet("output_aggregate_further_data\\04_dws_event_type_summary_1d.parquet")
df_04_dws_event_type_summary_1d_data.head()

    stat_date   event_type  event_cnt  event_ratio  event_ratio_pct
0  2026-07-01  create_task       3007       0.4644            46.44
1  2026-07-01   app_launch        969       0.1497            14.97
2  2026-07-01    view_list        923       0.1425            14.25
3  2026-07-01  search_task        894       0.1381            13.81
4  2026-07-01    app_close        330       0.0510             5.10

In [12]:
df_04_dws_event_type_summary_1d_data.columns

Index(['stat_date', 'event_type', 'event_cnt', 'event_ratio',
       'event_ratio_pct'],
      dtype='object')

In [13]:
df_05_dws_hour_active_summary_data = pd.read_parquet("output_aggregate_further_data\\05_dws_hour_active_summary.parquet")
df_05_dws_hour_active_summary_data.head()

    stat_date  active_hour  event_cnt  active_user_cnt
0  2026-07-01            0        246              243
1  2026-07-01            1        272              269
2  2026-07-01            2        246              244
3  2026-07-01            3        288              284
4  2026-07-01            4        304              300

In [14]:
df_05_dws_hour_active_summary_data.columns

Index(['stat_date', 'active_hour', 'event_cnt', 'active_user_cnt'], dtype='object')

In [15]:
df_06_dws_channel_region_summary_data = pd.read_parquet("output_aggregate_further_data\\06_dws_channel_region_summary.parquet")
df_06_dws_channel_region_summary_data.head()

    stat_date register_channel  province      city  active_user_cnt  event_cnt
0  2026-08-29  wechat_mini_app  Shanghai  Shanghai              198        510
1  2026-08-29       sina_weibo   Beijing   Beijing              188        502
2  2026-08-29      google_play  Shanghai  Shanghai              178        465
3  2026-08-29      google_play   Beijing   Beijing              178        447
4  2026-08-29          rednote   Beijing   Beijing              176        465

In [16]:
df_06_dws_channel_region_summary_data.columns

Index(['stat_date', 'register_channel', 'province', 'city', 'active_user_cnt',
       'event_cnt'],
      dtype='object')

In [17]:
df_07_dws_new_old_user_summary_data = pd.read_parquet("output_aggregate_further_data\\07_dws_new_old_user_summary.parquet")
df_07_dws_new_old_user_summary_data.head()

    stat_date  new_user_cnt  old_user_cnt
0  2026-07-01        4802.0           0.0
1  2026-07-02        2522.0        2335.0
2  2026-07-03        1297.0        3562.0
3  2026-07-04         659.0        4248.0
4  2026-07-05         359.0        4622.0

In [18]:
df_07_dws_new_old_user_summary_data.columns

Index(['stat_date', 'new_user_cnt', 'old_user_cnt'], dtype='object')

In [19]:
df_08_dws_user_retain_summary_data = pd.read_parquet("output_aggregate_further_data\\08_dws_user_retain_summary.parquet")
df_08_dws_user_retain_summary_data.head()

,first_active_date,total_new_users,day1_retained_users,day7_retained_users,day30_retained_users
0,2026-07-01,4802,2335,2511,2893
1,2026-07-02,2522,1260,1336,1521
2,2026-07-03,1297,642,684,785
3,2026-07-04,659,337,343,412
4,2026-07-05,359,164,190,218

In [20]:
df_08_dws_user_retain_summary_data.columns

Index(['first_active_date', 'total_new_users', 'day1_retained_users',
       'day7_retained_users', 'day30_retained_users'],
      dtype='object')

In [21]:
df_09_dws_user_feature_usage_summary_data = pd.read_parquet("output_aggregate_further_data\\09_dws_user_feature_usage_summary.parquet")
df_09_dws_user_feature_usage_summary_data.head()

,stat_date,remind_feature_usage_rate,subtask_usage_rate,due_date_setting_rate
0,2026-07-01,0.0,0.171120,0.323398
1,2026-07-02,0.0,0.167749,0.327797
2,2026-07-03,0.0,0.174284,0.331935
3,2026-07-04,0.0,0.166987,0.330274
4,2026-07-05,0.0,0.187401,0.350983

In [22]:
df_09_dws_user_feature_usage_summary_data.columns

Index(['stat_date', 'remind_feature_usage_rate', 'subtask_usage_rate',
       'due_date_setting_rate'],
      dtype='object')